version: "3.9"  # optional since v1.27.0
services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5111:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
  javabe:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_DB_PORT=5432
    depends_on:
      - postgres
  angularfe:
    build:
        context: ./dashboard-qube-web
        dockerfile: Dockerfile
    ports:
        - "4200:80"
    depends_on:
        - javabe